#!/bin/bash

set -u

# Source YNH helpers
. /usr/share/yunohost/helpers

app=${!#}

db_user=$app
db_name=$app
root_pwd=$(sudo cat /etc/yunohost/mysql)
domain=$(sudo ynh_app_setting_get $app domain)

mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"
sudo rm -rf /var/www/$app
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf
sudo rm -f /etc/cron.d/$app

sudo service nginx reload
